blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from blog.views import blogHome, blogPost, list_of_post_by_category, blogSearch

urlpatterns = [
    path('', blogHome, name='blogHome'),
    path('<str:slug>', blogPost, name='blogPost'),
    path('category/<slug>/', list_of_post_by_category, name='list_of_post_by_category'),
    path('search/', blogSearch, name='blogSearch'),
]

codextream/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from codextream import settings

admin.site.site_header = "CodeXtream Admin"
admin.site.site_title = "CodeXtream Admin Panel"
admin.site.index_title = "Welcome to CodeXtream Admin Panel"

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('course.urls')),
                  path('blog/', include('blog.urls')),
                  path('freepdf/', include('freepdf.urls')),
                  path('blog/', RedirectView.as_view(url='blog/')),
                  path('freepdf/', RedirectView.as_view(url='freepdf/')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', RedirectView.as_view(url='course/')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from django.views.generic import RedirectView

from course.views import contact, home, coursePost, search, category, CourseCategory, donate, privacy, team

urlpatterns = [
    path('course/', home, name='home'),
    path('course/<int:id>/<slug:slug>', coursePost, name='coursePost'),
    path('course/search/', search, name='search'),
    path('course/<str:query>', category, name='category'),
    path('course/categories/<int:pk>',CourseCategory.as_view(), name='course_category'),
    # path('course/<int:id>/<slug:slug>', CourseDetailView.as_view()),
   
    path('contact',contact,name='contact'),
    path('donate',donate,name='donate'),
    path('privacy',privacy,name='privacy'),
    path('team',team,name='team')
]

course/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.utils.text import slugify

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)

    class Meta:
        # enforcing that there can not be two categories under a parent with same slug
        # __str__ method elaborated later in post.  use __unicode__ in place of
        # __str__ if you are using python 2
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])
    
    def __str__(self):
        return self.name

class Course(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    img = models.ImageField(upload_to='thumbnails')
    slug = models.SlugField(max_length=300, null=True, blank=True)
    body_text = RichTextUploadingField(null=True)
    course_hour = models.CharField(max_length=100)
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE)
    upload_time = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    course_site_name = models.CharField(max_length=100, default='Site Name')
    url = models.URLField(null=True, blank=2)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.title

    def get_cat_list(self):
        k = self.category  # for now ignore this instance method

        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent
        for i in range(len(breadcrumb) - 1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i - 1:-1])
        return breadcrumb[-1:0:-1]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)


class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    phone = models.CharField(validators=[RegexValidator("^0?[5-9]{1}\d{9}$")], max_length=15, null=True, blank=True)
    email = models.EmailField(max_length=254)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, blank=True)
    
    
    def __str__(self):
        return 'Message from' + self.name

course/views.py
import time

from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.utils import timezone
from datetime import datetime
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib import messages
# Create your views here.

#
# def index(request):
#     msg = "Welcome to my website"
#     return HttpResponse(msg)
from django.views.generic import TemplateView, DetailView, ListView
from course.models import Course, Category, Contact


def home(request):
    post = Course.objects.all()
    cat_menu = Category.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(post, 8)

    week_ago = datetime.date.today() - datetime.timedelta(days=7)
    trends = Course.objects.filter(
        upload_time__gte=week_ago).order_by('-views')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    parms = {
        'cat_menu': cat_menu,
        'post': posts,
        'pop_post': Course.objects.order_by('-views'),
        'trends': trends[:5],
        'paginator': paginator,
        # 'posts': posts,
    }
    return render(request, 'course/home.html', parms)


def coursePost(request, id, slug):
    cat_menu = Category.objects.all().order_by('name')
    week_ago = datetime.date.today() - datetime.timedelta(days=7)
    trends = Course.objects.filter(
        upload_time__gte=week_ago).order_by('-views')
    try:
        course = Course.objects.get(pk=id, slug=slug)
    except:
        raise Http404("Post Does Not Exist")

    course.views += 1
    course.save()

    parms = {
        'cat_menu': cat_menu,
        'course': course,
        'trends': trends[:5],
    }
    return render(request, 'course/course_post.html', parms)


def search(request):
    cat_menu = Category.objects.all().order_by('name')
    context = {}
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    # q = request.GET.get('q')
    post = Course.objects.filter(
        Q(title__icontains=query) |
        Q(body_text__icontains=query) |
        Q(category__name__icontains=query)
    ).distinct()

    page = request.GET.get('page', 1)
    paginator = Paginator(post, 8)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    parms = {
        'cat_menu': cat_menu,
        'posts': posts,
        'title': f'{query}',
        'post_count': f'{post.count()}',
    }
    return render(request, 'course/search_post.html', parms)


def category(request, query):
    cat_menu = Category.objects.all().order_by('name')
    week_ago = datetime.date.today() - datetime.timedelta(days=7)
    accept = ['trending', 'popular']

    q = query.lower()
    if q in accept:
        if q == accept[0]:
            post = Course.objects.filter(
                upload_time__gte=week_ago).order_by('-views')
            page = request.GET.get('page', 1)
            paginator = Paginator(post, 8)
            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)
            parms = {
                'cat_menu': cat_menu,
                'posts': posts,
                'title': 'Trending Courses',
                'pop_post': Course.objects.order_by('-views')[:9],
            }
        elif q == accept[1]:
            post = Course.objects.order_by('-views')
            page = request.GET.get('page', 1)
            paginator = Paginator(post, 8)
            try:
                posts = paginator.page(page)
            except PageNotAnInteger:
                posts = paginator.page(1)
            except EmptyPage:
                posts = paginator.page(paginator.num_pages)
            parms = {
                'cat_menu': cat_menu,
                'posts': posts,
                'title': 'Popular Courses',
                'pop_post': Course.objects.order_by('-views')[:9],
            }
        else:
            messages.error(request, 'Not Found')

    return render(request, 'course/all.html', parms)


class CourseCategory(ListView):
    model = Category
    cat_menus = Category.objects.all().order_by('name')
    template_name = 'course/course_category.html'
    paginate_by = 8

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        cat_menu = Course.objects.filter(category=self.category)
        return cat_menu

    def get_context_data(self, **kwargs):
        return context


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        content = request.POST['content']
        if len(name) < 2 or len(email) < 3 or len(phone) < 10 or len(content) < 4:
            messages.error(request, 'Please fill the form correctly.')
        else:
            messages.success(request, 'Your message has been successfully sent.')
            contact = Contact(name=name, email=email, phone=phone, content=content)
            contact.save()
    return render(request, 'course/contact.html', {'cat_menu': cat_menu})


def donate(request):
    parms = {
        'cat_menu' : cat_menu
    }
    return render(request,'course/donate.html',parms)

def privacy(request):
    cat_menu = Category.objects.all().order_by('name')
    parms = {
        'cat_menu' : cat_menu
    }
    return render(request,'course/privacy_policy.html',parms)

def team(request):
    cat_menu = Category.objects.all().order_by('name')
    parms = {
        'cat_menu' : cat_menu
    }
    return render(request,'course/team.html',parms)

templates/course/all.html
{% extends 'base.html' %}
{% block homeactive %}active{% endblock %}
{% block title %} {{title}} {% endblock %}
{% block content %}
{% load static %}
   <div class="p-4">
    <div>
        <h2><span class="block-title">{{title}}</span></h2>
        <hr class="block-line">
    </div>
{% if cat_menu %}
    <div class="row">
        {% for course in posts %}
        <div class="col-md-6 col-lg-4 col-xl-3 ">
            <div class="card card-hover card-shadow mt-4" style="width: 18rem;">
                <a href="{% url 'coursePost' course.id course.slug %}"><img src="{{course.img.url}}" title="{{course.title}}" class="card-img-top img-thumbnail" style="height: 150px;" alt="..."></a>
                <p class="bottom-left"><span>{{course.course_site_name}}</span></p>
                <div class="card-body">

                    <p class="mb-2">
                        <span class="date-read"><span
                                class="fa fa-clock-o">&nbsp;&nbsp;</span>{{course.upload_time|timesince}} ago<span class="icon-star2"></span></span>
                    </p>
                    <a href="{% url 'course_category' course.category.pk %}">
                        <p class="topright"><button class="btn btn-info btn-sm">{{course.category}}</button></p></a>
                    <h5 class="card-title">
                        <a href="{% url 'coursePost' course.id course.slug %}" title="{{course.title}}"
                            style="text-decoration:none; color:black;">{{course.title|truncatechars:60}}
                        </a>
                    </h5>
                    <p>{{course.course_hour}} course</p>
                    <a href="{% url 'coursePost' course.id course.slug %}" class="btn btn-outline-success btn-block">Get
                        Course</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
       {% endif %}
       
  {% if posts %}     
         <ul class="pagination justify-content-center mt-3 ">
         {% if posts.has_previous %}
         <li><a href="?page=1"  class="page-link" >First</a></li>
         <li><a href="?page={{posts.previous_page_number}}" class="page-link" >Previous</a></li>
         {% endif %}
         {% for num in posts.paginator.page_range %}
         {% if posts.number == num %}
         <li class="active page-item"><a class="page-link active-page">{{num}}</a></li>
         {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
         <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
         {% endif %}
         {% endfor %}
         {% if posts.has_next %}
         <li class=page-item"><a href="?page={{posts.next_page_number}}" class="page-link">Next</a></li>
         <li class=page-item"><a href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>
         {% endif %}
         </ul>
{% endif %}  
</div>


{% endblock %}

templates/course/contact.html
{% extends 'base.html' %} 
{% block title %} Contact {% endblock %}
{% block content %}
<div class="container contact-form">
  <div class="contact-image">
    <img
      src="https://image.ibb.co/kUagtU/rocket_contact.png"
      alt="rocket_contact"
    />
  </div>
  <form action="/contact" method="post">
    {% csrf_token %}
    <h3>Contact Us</h3>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <input
            type="text"
            name="name"
            class="form-control"
            placeholder="Your Name *"
            value=""
          />
        </div>
        <div class="form-group">
          <input
            type="text"
            name="email"
            class="form-control"
            aria-describedby="emailHelp"
            placeholder="Your Email *"
            value=""
          />
        </div>
        <div class="form-group">
          <input
            type="text"
            name="phone"
            class="form-control"
            placeholder="Your Phone Number *"
            value=""
          />
        </div>
        <div class="form-group">
          <input
            type="submit"
            name="btnSubmit"
            class="btnContact"
            value="Send Message"
          />
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <textarea
            name="content"
            class="form-control"
            placeholder="Your Message *"
            style="width: 100%; height: 150px"
          ></textarea>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/course/course_category.html
{% extends 'base.html' %} 
{% block homeactive %}active{% endblock %} 
{% block title %} {{category.name}} {% endblock %}
{% block content %} 
{% load static %}

<div class="p-4">
  <div>
    <h2><span class="block-title">{{category.name}}</span></h2>
    <hr class="block-line" />
  </div>

  <div class="row">
    {% for course in course_list %}
    <div class="col-md-6 col-lg-4 col-xl-3">
      <div class="card card-hover card-shadow mt-4" style="width: 18rem">
        <img
          src="{{course.img.url}}"
          class="card-img-top img-thumbnail"
          style="height: 150px"
          alt="..."
        />
        <p class="bottom-left"><span>{{course.course_site_name}}</span></p>
        <div class="card-body">
          <p class="mb-2">
            <span class="date-read"><span class="fa fa-clock-o">&nbsp;&nbsp;</span>{{course.upload_time|timesince}} ago<span
                class="icon-star2"></span></span>
          </p>
          <p class="topright">
            <button class="btn btn-info btn-sm">{{course.category}}</button>
          </p>
          <h5 class="card-title">
            <a
              href="{% url 'coursePost' course.id course.slug %}"
              title="{{course.title}}"
              style="text-decoration: none; color: black">{{course.title|truncatechars:60}}
            </a>
          </h5>
          <p>{{course.course_hour}} course</p>
          <a href="{% url 'coursePost' course.id course.slug %}" class="btn btn-outline-success btn-block">Get Course</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
 
  {% if page_obj  %}
   <ul class="pagination justify-content-center mt-3 ">
         {% if page_obj.has_previous %}
         <li><a href="?page=1"  class="page-link" >First</a></li>
         <li><a href="?page={{page_obj.previous_page_number}}" class="page-link" >Previous</a></li>
         {% endif %}
         {% for num in page_obj.paginator.page_range %}
         {% if page_obj.number == num %}
         <li class="active page-item"><a class="page-link active-page">{{num}}</a></li>
         {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
         <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
         {% endif %}
         {% endfor %}
         {% if page_obj.has_next %}
         <li class=page-item"><a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a></li>
         <li class=page-item"><a href="?page={{page_obj.paginator.num_pages}}" class="page-link">Last</a></li>
         {% endif %}
         </ul>
    {% endif %}
</div>

{% endblock %}

templates/course/course_post.html
{% extends 'base.html' %}
{% block homeactive %}active{% endblock %}
{% block title %} {{course.title}} {% endblock %}
{% block content %}
{% load static %}

{% if cat_menu %}
<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="page-header mt-5">
						<h3>{{course.title}}</h3>
						<p>Posted by <span class="glyphicon glyphicon-user"></span> <a href="#">{{course.user.username}}</a> on
                            <span class="glyphicon glyphicon-time"></span>{{course.upload_time}}</p>
					</div>
				</div>
			</div>
    <hr>
    <div class="row">
				<div class="col-sm-8">

					<!-- Image -->
					<figure class="margin-b-2">
						<img class="img-responsive img-fluid" src="{{course.img.url}}" alt="">

					</figure>
                    <div class="container">
					{{course.body_text|safe}}
                        </div>

                      <div>
                    <a href="https://t.me/CodeXtream" target="_blank">
                        <button class="enrollbtn btn btn-sm"><i class="fa fa-paper-plane"></i>  &nbsp;Join Our Telegram Group
                        </button></a>
                </div>

                <div>
                    <a href="{{ course.url }}" target="_blank">
                        <button class="enrollbtn btn btn-sm"><i class="fa fa-sign-in fa-md"></i>&nbsp;&nbsp;Enroll Now
                        </button></a>
                </div>


                      <h3 class="mt-3 mb-3" style="text-align:center;">Join Us</h3>
                <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Join our WhatsApp group for referral :</th>
      <th scope="col"><a href="https://chat.whatsapp.com/BOqnSDvsARdE0Kc2JlOrYH" target="_blank">Click Here</a> </th>
    </tr>
  <tr>
      <th scope="col">Join our telegram group :</th>
      <th scope="col"><a href="https://t.me/CodeXtream" target="_blank">Click Here</a> </th>
    </tr>
  <tr>
      <th scope="col">Telegram group(Free Online Courses) :</th>
      <th scope="col"><a href="https://t.me/CodeXtream" target="_blank">Click Here</a> </th>
    </tr>
  <tr>
      <th scope="col">Join our LinkedIn group for referral : </th>
      <th scope="col"><a href="" target="_blank">Click Here</a> </th>
  </tr>
    <tr>
      <th scope="col">Facebook Group : </th>
      <th scope="col"><a href="https://www.facebook.com/groups/691451751469034/?ref=share" target="_blank">Click Here</a> </th>
  </tr>
   <tr>
      <th scope="col">Follow us on LinkedIn : </th>
      <th scope="col"><a href="https://www.linkedin.com/in/code-xtream-655b971b5" target="_blank">Click Here</a> </th>
  </tr>
   <tr>
      <th scope="col">Follow us on Twitter : </th>
      <th scope="col"><a href="https://twitter.com/code_xtream?s=09" target="_blank">Click Here</a> </th>
  </tr>
   <tr>
      <th scope="col">Follow us on Instagram : </th>
      <th scope="col"><a href="https://instagram.com/codextreamofficial?igshid=mqh812jbb76l" target="_blank">Click Here</a> </th>
  </tr>
  </thead>

</table>
					<hr>



				</div>
				<div class="col-sm-4">
					<!-- Search -->
			     <div class="card">

          <h5 class="card-header">Search</h5>
          <div class="card-body">
              <form action="{% url 'search' %}">
            <div class="input-group">
              <input type="search" class="form-control" aria-label="Search" placeholder="Search for Courses" name="q" required>
              <span class="input-group-append">
                <button class="btn btn-secondary" type="submit" title="search">Search</button>
              </span>
            </div>
                  </form>
          </div>
        </div>

					<!-- Panel -->
					<div class="panel panel-default mt-4">
                       <div class="section-title trending p-2" style="color:white; text-align:center;">
              <h4>Trending Posts</h4>
          </div>
                        <div class="panel-body">
					<ol class="list-unstyled mb-0">

                {% for post in trends|slice:":5" %}
                <div class="media mt-3">
                    <img src="{{ post.img.url }}" alt="" class="mr-2" style="width:70px; height:50px;">
                    <div class="media-body small">
                      <div class="d-flex justify-content-between align-items-center w-100">
                          <a href="{% url 'coursePost' post.id post.slug %}" style="text-decoration:none; color:#0d0d0d;"><h6 class="card-title blogpost-hover">{{ post.title }}</h6></a>
                      </div>
                    </div>
                  </div>
                <hr>
                {% endfor %}

            </ol>
					</div>
                    </div>
                    <a href="{% url 'category' 'trending' %}" class="btn btn-treand mb-4">See All Trending Courses<span class="icon-keyboard_arrow_right"></span></a>
				</div>
			</div>
</div>
{% endif %}
{% endblock %}

templates/course/donate.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Donate {% endblock %}
{% block donateactive %}active{% endblock %}
{% block content %}
<div class="container p-5">
    <h1 class="mb-4">To All Student Around the world,</h1>
    <h6 class="mb-4" style="line-height:30px;"><b>CodeXtream</b> is something special. It is like a Free Courses or a public park. 
        It is a place we can all go to think, to learn, to share our knowledge with others for no cost since 2020</h6>
    <h6 class="mb-4" style="line-height:30px;">However our funds are becoming limited, we wish to keep <b>CodeXtream</b> thriving for years to come, to preserve free, 
        accessible knowledge to our users and even expand to be able to provide for those beyond the scope of the interweb.</h6>
    <h6 class="mb-4" style="line-height:30px;">In this case, we are asking for your help.
        A donation of any size would help <b>CodeXtream</b> reach goals that will help more than just its users.</h6>
    <h6 class="mb-4" style="line-height:30px;">Thank you for taking the time to read. We are grateful for your time and consideration.</h6>
    <h6 class="mb-4" style="line-height:30px;">Wishing you all the best.</h6>
    <h6 class="mb-4" style="line-height:30px;">The <b>CodeXtream</b> Team</h6>

    <hr>
    <img src="{% static 'images/paytm.jpg' %}" style="height:500px; width:300px;" class="mt-3 paytm-center img-thumbnail" alt="Image Not Found">

</div>
{% endblock %}

templates/course/home.html
{% extends 'base.html' %}
{% block homeactive %}active{% endblock %}
{% block title %} CodeXtream {% endblock %}
{% block content %}
{% load static %}

<div class="p-4">
    <div>
        <h2><span class="block-title">Latest Course</span></h2>
        <hr class="block-line">
    </div>
    <div style="text-align:center;">
        <h5>Join to Our Telegram Group: <a href="https://t.me/CodeXtream" target="_blank">Click Here</a></h5>
    </div>

{% if cat_menu %}
    <div class="row p-1 mb-4">
        {% for course in post %}
        <div class="col-md-6 col-lg-4 col-xl-3 ">
            <div class="card card-hover card-shadow mt-4" style="width: 18rem;">
                <a href="{% url 'coursePost' course.id course.slug %}"><img src="{{course.img.url}}" title="{{course.title}}" class="card-img-top img-thumbnail" style="height: 150px;" alt="{{course.title}}"></a>
                <p class="bottom-left"><span>{{course.course_site_name}}</span></p>
                <div class="card-body">

                    <p class="mb-2">
                        <span class="date-read"><span
                                class="fa fa-clock-o">&nbsp;&nbsp;</span>{{course.upload_time|timesince}} ago<span
                                class="icon-star2"></span></span>
                    </p>
                    <a href="{% url 'course_category' course.category.pk %}">
                        <p class="topright"><button class="btn btn-info btn-sm">{{course.category}}</button></p>
                    </a>
                    <h5 class="card-title">
                        <a href="{% url 'coursePost' course.id course.slug %}" title="{{course.title}}"
                            style="text-decoration:none; color:black;">{{course.title|truncatechars:60}}
                        </a>
                    </h5>
                    <p>{{course.course_hour}} course</p>
                    <a href="{% url 'coursePost' course.id course.slug %}" class="btn btn-outline-success btn-block">Get
                        Course</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endif %}

    {% if post %}
   <ul class="pagination justify-content-center mt-3 ">
         {% if post.has_previous %}
         <li><a href="?page=1"  class="page-link" >First</a></li>
         <li><a href="?page={{post.previous_page_number}}" class="page-link" >Previous</a></li>
         {% endif %}
         {% for num in post.paginator.page_range %}
         {% if post.number == num %}
         <li class="active page-item"><a class="page-link active-page">{{num}}</a></li>
         {% elif num > post.number|add:'-3' and num < post.number|add:'3' %}
         <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
         {% endif %}
         {% endfor %}
         {% if post.has_next %}
         <li class=page-item"><a href="?page={{post.next_page_number}}" class="page-link">Next</a></li>
         <li class=page-item"><a href="?page={{post.paginator.num_pages}}" class="page-link">Last</a></li>
         {% endif %}
         </ul>
{% endif %}
    <div class="row">
        <div class="col-xl-8 text-justify ">

            					<div class="panel panel-default mt-4">
                       <div class="section-title trending p-2" style="color:white; text-align:center;">
              <h4>Popular Courses</h4>
          </div>
                        <div class="panel-body">
					<ol class="list-unstyled mb-0">

                {% for post in pop_post|slice:":5" %}
                <div class="media mt-3">
                    <img src="{{ post.img.url }}" alt="" class="mr-2" style="width:110px; height:70px;">
                    <div class="media-body small">
                      <div class="d-flex justify-content-between align-items-center w-100">
                          <a href="{% url 'coursePost' post.id post.slug %}" style="text-decoration:none; color:#0d0d0d;"><h6 class="card-title blogpost-hover">{{ post.title }}</h6></a>
                      </div>
                        <div class="post-meta">

                            <span class="date-read">{{post.upload_time}}<span class="icon-star2"></span></span>
                        </div>
                    </div>
                  </div>
                <hr>
                {% endfor %}
 <p>
                <a href="{% url 'category' 'popular' %}" class="btn btn-treand">See All Popular Courses<span
                        class="icon-keyboard_arrow_right"></span></a>
            </p>
            </ol>
					</div>
                    </div>
        </div>

        <div class="col-xl-4">
       <div class="panel panel-default mt-4">
                    <div class="section-title trending p-2" style="color:white; text-align:center;">
              <h4>Trending Courses</h4>
          </div>
              <div class="panel-body">
					<ol class="list-unstyled mb-0">

                {% for post in pop_post|slice:":5" %}
                <div class="media mt-3">
                    <img src="{{ post.img.url }}" alt="" class="mr-2" style="width:110px; height:70px;">
                    <div class="media-body small">
                      <div class="d-flex justify-content-between align-items-center w-100">
                          <a href="{% url 'coursePost' post.id post.slug %}" style="text-decoration:none; color:#0d0d0d;"><h6 class="card-title blogpost-hover">{{ post.title }}</h6></a>
                      </div>
                        <div class="post-meta">

                            <span class="date-read">{{post.upload_time}}<span class="icon-star2"></span></span>
                        </div>
                    </div>
                  </div>
                <hr>
                {% endfor %}
 <p>
                <a href="{% url 'category' 'trending' %}" class="btn btn-treand">See All Trending Courses<span
                        class="icon-keyboard_arrow_right"></span></a>
            </p>
            </ol>
					</div>
       </div>
        </div>
    </div>
</div>
{% endblock %}